export const surface = {
  name: 'PipeFlow Academy',
  domain: 'pipeflowacademy.com',
  port: 3181,
  headline: 'Training pathways for infrastructure professionals.',
  tagline: 'Training, readiness, and field systems pathways',
  footerDescription: 'public education demo for training paths, certifications, and readiness concepts.',
  safetyNote: 'Public demo surface. Private datasets, credentials, and internal implementation details are not included.',
  siblingSurface: {
    label: 'Systems',
    localUrl: 'http://127.0.0.1:3180',
  },
  navItems: [
    { path: '/', label: 'Home' },
    { path: '/learn', label: 'Learn' },
    { path: '/certifications', label: 'Certifications' },
    { path: '/certification-progress', label: 'Progress' },
    { path: '/skills', label: 'Skills' },
    { path: '/skills-map', label: 'Skills Map' },
    { path: '/field-readiness', label: 'Readiness' },
    { path: '/training-gaps', label: 'Gaps' },
    { path: '/workflow-labs', label: 'Workflow Labs' },
    { path: '/career-paths', label: 'Career Paths' },
    { path: '/apprenticeships', label: 'Apprenticeships' },
    { path: '/electrical', label: 'Electrical' },
    { path: '/plumbing', label: 'Plumbing' },
    { path: '/hvac', label: 'HVAC' },
    { path: '/datacenter', label: 'Datacenter' },
    { path: '/field-labs', label: 'Field Labs' },
    { path: '/ai-tools', label: 'AI Tools' },
    { path: '/instructors', label: 'Instructors' },
    { path: '/business', label: 'Business' },
  ],
};
